# Generated by Django 3.1 on 2020-08-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gendenter',
            new_name='gender',
        ),
    ]
